version: '3.9'

services:
  redis:
    image: bitnami/redis:7.2.3
    restart: unless-stopped
    ports:
      - '6379:6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis-data:/bitnami/redis/data

  mongodb:
    image: bitnami/mongodb:7.0.4
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      # General
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DATABASE=mongodb
      - MONGODB_USERNAME=mongodb
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      # Replica Set
      - MONGODB_ADVERTISED_HOSTNAME=host.docker.internal
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=${MONGODB_REPLICA_SET_KEY}
      - MONGODB_REPLICA_SET_NAME=rs0
    volumes:
      - mongodb-data:/bitnami/mongodb
{% for number in range(KAFKA_CLUSTER_NODES) %}
  kafka-{{ number }}:
    image: bitnami/kafka:3.6.1
    restart: unless-stopped
    ports:
      - '1000{{ number }}:9094'
    environment:
      # General
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_AUTO_LEADER_REBALANCE_ENABLE=true
      # KRaft
      - KAFKA_CFG_NODE_ID={{ number }}
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=
{%- set comma = joiner(",") %}
{%- for n in range(KAFKA_CLUSTER_NODES) %}{{ comma() }}{{ "{0}@kafka-{0}:9093".format(n) }}{%- endfor %}
      - KAFKA_KRAFT_CLUSTER_ID=${KAFKA_KRAFT_CLUSTER_ID}
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-{{ number }}:9092,EXTERNAL://host.docker.internal:1000{{ number }}
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      # Clustering
      - KAFKA_CFG_NUM_PARTITIONS={{ KAFKA_CLUSTER_NODES * 4 }}
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR={{ KAFKA_CLUSTER_NODES }}
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR={{ KAFKA_CLUSTER_NODES }}
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR={{ KAFKA_CLUSTER_NODES }}
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR={{ KAFKA_CLUSTER_NODES - 1 }}
      - KAFKA_CFG_MIN_INSYNC_REPLICAS={{ KAFKA_CLUSTER_NODES - 1 }}
    networks:
      - kafka-net
    volumes:
      - kafka-{{ number }}:/bitnami
{% endfor %}
volumes:
  redis-data:
    driver: local

  mongodb-data:
    driver: local
{% for number in range(KAFKA_CLUSTER_NODES) %}
  kafka-{{ number }}:
    driver: local
{% endfor %}
networks:
  kafka-net:
    driver: bridge
